import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";

const inter = Inter({ subsets: ["latin"] });

const Canopee = localFont({
  src: "./fonts/Canopee.ttf",
  variable: "--font-canopee",
});
const Editorial = localFont({
  src: "./fonts/EditorialNew-Regular.ttf",
  variable: "--font-editorial",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${Canopee.variable} ${Editorial.variable}`}>
      <body>{children}</body>
    </html>
  );
}
